name: fitbasix
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+13

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1
  dio: ^4.0.0
  firebase_crashlytics: ^2.5.1
  firebase_analytics: ^9.1.0
  firebase_remote_config: ^2.0.2
  flutter_svg: ^1.0.0
  google_fonts: ^2.1.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.11
  sign_in_with_apple: ^3.3.0
  http: ^0.13.4
  shimmer: ^2.0.0
  flutter_screenutil: ^5.0.3
  photo_manager: ^2.0.8
  video_thumbnail: ^0.4.3
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  uuid: ^3.0.5
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  flutter_blurhash: ^0.6.0
  flutter_holo_date_picker: ^1.0.1+2
  flutter_ruler_picker: ^1.0.2
  intl: ^0.17.0
  cometchat: ^3.0.1
  mime:

#  quickblox_sdk: ^0.6.7-beta
  crypt: ^4.2.1
  readmore: ^2.1.0
  health: ^3.4.3
  syncfusion_flutter_charts: ^19.4.48
  liquid_progress_indicator: ^0.4.0
  getwidget: ^2.0.4
  dropdown_button2: ^1.1.1
  video_player: ^2.2.18
  file_picker: ^4.4.0
  mime_type: ^1.0.0
  permission_handler:
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  flutter_switch: ^0.3.2
  open_file: ^3.2.1
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.3.2
  connectycube_flutter_call_kit: ^2.0.2
  percent_indicator: ^4.0.0
  syncfusion_flutter_gauges: ^19.4.54
  awesome_notifications: ^0.6.21
  images_picker: ^1.2.10
  flutter_time_picker_spinner: ^2.0.0
  lottie: ^1.2.2
  shared_preferences_ios: ^2.1.0
  shared_preferences_android: ^2.0.11
  uni_links: ^0.5.1
  flutter_launcher_icons: ^0.9.2
  sentry_flutter: ^6.5.1
  visibility_detector: ^0.2.2
  store_redirect: ^2.0.1
  connectivity: ^3.0.6
  field_suggestion: ^0.2.3
  flutter_inappwebview: ^5.3.2
  enx_flutter_plugin: ^2.0.7
  selectable_autolink_text: ^2.3.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_info: ^2.0.3

#flutter_native_splash:
#  background_image: "assets/log_in/welcome_image.png"
#  background_image_dark: "assets/log_in/welcome_image.png"
#  fullscreen: true
#  ios_content_mode: scaleAspectFill
#  android: true
#  ios: true
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translation/
    - assets/Icons/
    - assets/images/
    - assets/get_trained/
    - assets/menuSlider/
    - assets/home/
    - assets/settings/
    - assets/message/
    - assets/mytrainers/
    - assets/bmrscreen/
    - assets/plans/
    - assets/log_in/
    - assets/gif/
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
